name: Assert Lockfiles (`bun.lockb`, `yarn.lock`)

on:
  - pull_request

jobs:
  build:
    timeout-minutes: 40
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: moonrepo/setup-toolchain@v0
        with:
          # A GitHub action that sets up an environment for proto and moon.
          # - Installs proto globally so that installed tools can also be executed globally.
          # - Caches the toolchain (~/.proto) so subsequent runs are faster.
          # - Hashes .prototools and .moon/toolchain.yml files to generate a unique cache key.
          # - Cleans the toolchain before caching to remove unused or stale tools.
          # See: https://github.com/moonrepo/setup-toolchain
          auto-install: true

      - name: Check Lockfiles Diff
        # See https://zenn.dev/watany/articles/e21a54cf3d56d8
        run: diff <(bun bun.lockb) yarn.lock
