name: Test Storybook (turbo)

on:
  - pull_request

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  sbtest:
    timeout-minutes: 40
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: moonrepo/setup-toolchain@v0
        with:
          # A GitHub action that sets up an environment for proto and moon.
          # - Installs proto globally so that installed tools can also be executed globally.
          # - Caches the toolchain (~/.proto) so subsequent runs are faster.
          # - Hashes .prototools and .moon/toolchain.yml files to generate a unique cache key.
          # - Cleans the toolchain before caching to remove unused or stale tools.
          # See: https://github.com/moonrepo/setup-toolchain
          auto-install: true

      - name: Install
        run: bun install --frozen-lockfile

      - name: Install Playwright with Dependencies
        run: bun x playwright install --with-deps

      - name: Test Storybook with Turbo
        run: bun x turbo sb:test
